include $(ROOT)/config.mk

LOCAL_MODULE := libwebrtc_vad.a
LOCAL_SRC_FILES := \
    webrtc_vad.c \
    vad_core.c \
    vad_filterbank.c \
    vad_gmm.c \
    vad_sp.c


include $(ROOT)/build_library.mk

