include $(ROOT)/config.mk

LOCAL_MODULE := libwebrtc_apm_utility.a
LOCAL_SRC_FILES := \
    fft4g.c \
    ring_buffer.c \
    delay_estimator.c \
    delay_estimator_wrapper.c


include $(ROOT)/build_library.mk

