include $(ROOT)/config.mk

LOCAL_MODULE := libwebrtc_apm.a
LOCAL_SRC_FILES := \
    audio_buffer.cc \
    audio_processing_impl.cc \
    echo_cancellation_impl.cc \
    echo_control_mobile_impl.cc \
    gain_control_impl.cc \
    high_pass_filter_impl.cc \
    level_estimator_impl.cc \
    noise_suppression_impl.cc \
    processing_component.cc \
    splitting_filter.cc \
    voice_detection_impl.cc


include $(ROOT)/build_library.mk

